server:
  port: 9000

spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:final-project
    username: fs7
    password:

  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/finalproject_db?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

---
